const appData = {
  pointsData: [
    {
      id: 12332,
      name: "Kansas City, MO",
      state: "Missouri",
      title: "KANSAS CITY, MO",
      translateProp: "translate( 10%, -55%)",
      coordinates: [-94.578331, 39.099724],
      description:"The Kansas City Streetcar gets people out of their cars and into the community.",
      vimeoVideo: "https://player.vimeo.com/video/830670385",
      youtubeVideo: "",
      image: "",
      link:"https://www.chargingusforward.com/kc-ride",
    },
    {
      id: 999,
      name: "Pittsburg",
      state: "Pennsylvania",
      title: "Pittsburgh, PA",
      coordinates: [-79.9928601184325, 40.440514432625896],
      translateProp: "translate(73%, -68%)",
      description: `Pittsburgh's POGOH e-bike share program provides bike access for work, errands, and leisure.`,
      vimeoVideo: "https://player.vimeo.com/video/842673721",
      youtubeVideo: "",
      image: "",
      link:"https://www.chargingusforward.com/pogoh",

    },
    {
      id: 312,
      name: "Denver",
      state: "Colorado",
      title: "Denver, CO",
      translateProp: "translate(-35%, -75%)",
      coordinates: [-104.9903, 39.7392],
      description: "Colorado Electric Scenic & Historic Byways",
      vimeoVideo: "https://player.vimeo.com/911006737",
      youtubeVideo: "",
      image: "",
      link:"https://www.chargingusforward.com/colorado-electric-byways",
    },
    {
      id: 4,
      name: "Minneapolis",
      state: "Minnesota",
      title: "Minneapolis, MN",
      translateProp: "translate(15%, -85%)",
      coordinates: [-93.265, 44.9778],
      description: `Minnesota Clean School Bus Programs`,
      youtubeVideo: "",
      vimeoVideo:"https://player.vimeo.com/1038026387?share=copy",
      link:"https://www.chargingusforward.com/minnesota-esb-programs",
      image: "",
    },
    {
      id: 5,
      name: "Texas Issue Brief",
      state: "Texas",
      title: "TEXAS ISSUE BRIEF",
      translateProp: "translate(-20%, -16%)",
      coordinates: [-99.9018, 31.9686],
      description: `Clean Trucks`,
      youtubeVideo: "",
      link:"https://www.chargingusforward.com/texas-issue-brief",
      image: "https://images.squarespace-cdn.com/content/v1/602e01c0d559ed484f74b59e/bbe67340-685d-4138-bdac-625067698821/Issue+Brief+-+Clean+Trucks+Hit+the+Road+in+Texas+%281%29.jpg?format=500w",
    },
    {
      id: 6,
      name: "Georgia Issue Brief",
      state: "Georgia",
      title: "GEORGIA ISSUE BRIEF",
      translateProp: "translate(82%, -21%)",
      coordinates: [-82.9001, 32.1656],
      description: `EV Manufacturing`,
      youtubeVideo: "",
      image: "Thumbnail of report cover",
      link:"https://www.chargingusforward.com/georgia-issue-brief"
    },
    {
      id: 7,
      name: "Ohio Issue Brief",
      state: "Ohio",
      title: "OHIO ISSUE BRIEF",
      translateProp: "translate(85%, -69%)",
      coordinates: [-82.9071, 40.4173],
      description: `Clean Ports`,
      youtubeVideo: "",
      image: "Thumbnail of report cover",
    },
    {
      id: 8,
      name: "Arizona Issue Brief",
      state: "Arizona",
      title: "ARIZONA ISSUE BRIEF",
      translateProp: "translate(-81%, -33%)",
      coordinates: [-111.0937, 34.0489],
      description: `Charging Infrastructure`,
      youtubeVideo: "",
      image: "#",
      link:"https://www.chargingusforward.com/arizona-issue-brief"
    },
  ],

  activeCoordinates: [],
};

export default appData;
